### ISSUE TITLE
DKIM DNS Failure

### ISSUE THREAD

**Issue by mario-one** [cammurray/orca#132] opened 2021-04-30 21:20 UTC
I have been finalizing as many Orca recommendations as possible and I have run into an issue with the DKIM-DNS Records section.    We have DNS records for several of the domains, but the report says we do not. I validated that the DKIM records are there as needed, I also copied an pasted from O365 to our DNS to make sure and still the report says it cannot find it. Checked the domains against mxtoolbox.com which shows the DKIM selector entry is there. 

When I go to the threat policy the "Sign messages for this domain with DKIM signatures" is enabled

**Comment by karashah1** [comment] 2021-08-23 07:08
Issue resolved. 

Root cause: Environmental issue - ORCA was hitting internal DNS servers.
Solution: Run ORCA on a different machine.

**Comment by BrianKnipfel** [comment] 2022-01-26 16:40
We have some domains that do not send email setup but they show up as failures with yellow warning.  IF email is NOT configured/enabled for the domain there is no need to check some setting. Can this be looked at to optimize?

**Comment by NehavPandey** [comment] 2022-02-07 11:16
Closing this thread as original is resolved @BrianKnipfel Can you open a new issue for feature request

**Closed by NehavPandey** 2022-02-07 11:16 UTC
