### ISSUE TITLE
Add recommendation for anti-spam policies

### ISSUE THREAD

**Issue by worldsdream** [cammurray/orca#251] opened 2023-07-27 13:28 UTC
It should warn us or even give an error when you add a user or domain to the "allowed and blocker senders and domains" section.

![GitHub](https://github.com/cammurray/orca/assets/12443285/896160a7-4518-4486-9851-88fc34977360)

Microsoft recommends not adding a domain or email over there:

The least desirable option is to use the allowed sender list or allowed domain list in anti-spam policies. You should avoid this option if at all possible because senders bypass all spam, spoof, phishing protection (except high confidence phishing), and sender authentication (SPF, DKIM, DMARC). This method is best used for temporary testing only.

https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide#use-allowed-sender-lists-or-allowed-domain-lists

The recommendation is:

https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide#use-mail-flow-rules

This is also the case for Use the IP Allow list.

Please have a look over here:

https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365

**Comment by cammurray** [comment] 2023-07-31 22:15
Hi @worldsdream 

There should already be a check for domains/senders in the allow* settings in the spam policies.

Are you saying that this check is not functioning?

**Comment by worldsdream** [comment] 2023-07-31 22:54
I didn’t notice anything about it.

I have some domains in the allow list, and no warning or mention that I shoudln’t use that method.

Let me double check and come back here.

**Comment by worldsdream** [comment] 2023-08-01 15:29
Double-checked it again.

Ths is how it shows in the report:

![info1](https://github.com/cammurray/orca/assets/12443285/ada441e6-3963-48d8-9a13-6d16526d8360)

It should show the domain "gmail.com" and report it's not good that it's in there.

![info2](https://github.com/cammurray/orca/assets/12443285/610098fb-ff09-4ced-90b2-7fcec20aac24)

**Comment by cammurray** [comment] 2023-08-29 03:50
Ok, confirmed this bug - this is a PowerShell thing and is due to the allowed domains only being 1 domain. As soon as you put more than 1, the check fails.

Simply, we store your domains in a variable and then use a .count on that variable - but if there is only one domain, that variable no longer becomes an array and therefor .count is null. So we need to force it as an array, which is an easy fix. Will check in the code for the 2.6 release.

**Comment by cammurray** [comment] 2023-08-29 03:54
Checked in to orca2.6 code in #254

**Closed by cammurray** 2023-08-29 03:54 UTC
Labels: bug
