### ISSUE TITLE
Had to use Install-Module -Name ExchangeOnlineManagement

### ISSUE THREAD

**Issue by SusanBradley** [cammurray/orca#4] opened 2020-01-09 18:31 UTC
I couldn't use the  http://aka.ms/exopsmodule  I had to use
Install-Module -Name ExchangeOnlineManagement .  It kept erroring out that the psmodule.client.exe.manifest did not succeed.  Once I used the other Powershell command it worked like a champ.  Just sharing in case others hit this.

**Comment by cammurray** [comment] 2020-01-11 03:07
@SusanBradley we support the new REST enabled module (Install-Module -Name ExchangeOnlineManagement) and also the old RPS module during this transitioning phase. Both are very valid and we will eventually, once the REST enabled module is GA remove all references to the old RPS module.

Please note because the old RPS module (http://aka.ms/exopsmodule) uses an app package mechanism that is browser dependant, that website will only work on certain browsers (for instance, Chrome won't work).

Closing this as I suspect that it's not a bug, just an issue with the old RPS module.

**Closed by cammurray** 2020-01-11 03:07 UTC

**Comment by SusanBradley** [comment] 2020-01-11 04:15
Edge beta is my default browser.
