### ISSUE TITLE
Module is not compatible with MacOS 12.6

### ISSUE THREAD

**Issue by adrischw** [cammurray/orca#161] opened 2022-10-14 17:45 UTC
I tried to install and execute the Get-ORCAReport. Installation of the module was successful with my running version of Powershell on Mac.

Name                           Value
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

After executing the Get-ORCAReport I was running in two errors:
First error: Cmd'let Resolve-DnsName was not recognized.
Therefore I installed the DnsClient-PS Module from PSGallery
`Install-Module -Name DnsClient-PS`
Because this module only knows Resolve-Dns, I added an alias to get Resolve-DnsName executed.
`Set-Alias Resolve-DnsName -Value Resolve-Dns`

Second error: Variable $IsMac doesn't exist in MacOS, $IsMacOS is the correct variable listed on Set-Variable.
I just set the variable and it was a good workaround.
`$IsMac = $true`

I'd suggest to document the first error, so Mac/Linux Users have a chance to find an alternative.
Second error is clearly something to fix in the script, where newer MacOS releases would profit from.

Best regards

**Comment by cammurray** [comment] 2023-05-02 02:10
Hey @adrischw there's two issues here so just separating out..

First off sorry for the delay, i've been on paternity leave and there's a team now that maintains this, but they might be under load at the moment so i'm just helping out to clear some of this backlog.

The $IsMac = $True is a dupe of #170 and i've fixed that ready for 2.3. Once i've got some of the low hanging fruit out the door i'll check that in to master and that should be good to go.

The issue with Resolve-DnsName is that we are just silently failing that command, because we expect it to fail when SPF/DKIM records don't exist. The problem isn't specific to MacOS and thanks for raising it, i've gone ahead and created a specific bug for that #175 

So as part of this is fixed and the other part will be completed with #175 i'll close this off, thanks again for your report.

**Closed by cammurray** 2023-05-02 02:10 UTC
